In [263]:
import os
import music21 

In [ ]:
mxl_files = os.listdir('../data/quartet_raw')
len(mxl_files)

In [3]:
for (num, file) in enumerate(mxl_files):
    print(f'Encoding file #{num}: "{file}"\t', end='')
    try:
        music21.converter.parse(f'../data/quartet_raw/{file}').write('midi', f'../data/midis/{file}.midi')
        print('Done!')
    except (ZeroDivisionError, TypeError) as e:
        print(f'Parsing error: {e}. Skipping...')
    
    

Encoding file #0: "String Quartet No. 13 in B flat major.mscx.mxl"	Done!
Encoding file #1: "String Quartet No. 13 in B flat major_1.mscx.mxl"	Done!
Encoding file #2: "String Quartet No. 14 in C sharp minor.mscx.mxl"	Done!
Encoding file #3: "String Quartet No. 14 in C sharp minor_1.mscx.mxl"	Done!
Encoding file #4: "String Quartet No. 15 in A minor.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 546 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 577 P2


Done!
Encoding file #5: "String Quartet No. 15 in A minor_1.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 546 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 577 P2


Done!
Encoding file #6: "String Quartet No. 16 in F major, Opus 135.mscx.mxl"	Done!
Encoding file #7: "String Quartet No. 16 in F major, Opus 135_1.mscx.mxl"	Done!
Encoding file #8: "String Quartet no.1 - 1. Allegro.mscx.mxl"	Done!
Encoding file #9: "String Quartet no.1 - 1. Allegro_1.mscx.mxl"	Done!
Encoding file #10: "String Quartet no.1 - 2. Andante.mscx.mxl"	Done!
Encoding file #11: "String Quartet no.1 - 2. Andante_1.mscx.mxl"	Done!
Encoding file #12: "String Quartet no.1 - 4. Allegro.mscx.mxl"	Done!
Encoding file #13: "String Quartet no.1 - 4. Allegro_1.mscx.mxl"	Done!
Encoding file #14: "String Quartet No.1 Mvt.1.mscx.mxl"	Done!
Encoding file #15: "String Quartet No.1 Mvt.1_1.mscx.mxl"	Done!
Encoding file #16: "String Quartet No.1 Mvt.2.mscx.mxl"	Done!
Encoding file #17: "String Quartet No.1 Mvt.2_1.mscx.mxl"	Done!
Encoding file #18: "String Quartet No.1 Mvt.3.mscx.mxl"	Done!
Encoding file #19: "String Quartet No.1 Mvt.3_1.mscx.mxl"	Done!
Encoding file #20: "String Quartet No.1 

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 7 P1


Done!
Encoding file #98: "String_Quaret_1.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 7 P1


Done!
Encoding file #99: "string_quartet collections.mscx.mxl"	Done!
Encoding file #100: "STRING_QUARTET Mvt 2.mscx.mxl"	Done!
Encoding file #101: "String_Quartet orioer.mscx.mxl"	Done!
Encoding file #102: "String_Quartet orioer_1.mscx.mxl"	Done!
Encoding file #103: "String_Quartet,_Third_Movement.mscx.mxl"	Done!
Encoding file #104: "String_Quartet,_Third_Movement_1.mscx.mxl"	Done!
Encoding file #105: "String_Quartet,_Third_Movement_2.mscx.mxl"	Done!
Encoding file #106: "String_Quartet,_Third_Movement_3.mscx.mxl"	Done!
Encoding file #107: "String_Quartet.mscx.mxl"	Done!
Encoding file #108: "string_quartet1.mscx.mxl"	Done!
Encoding file #109: "String_Quartett_-_The_Void_-_1st_mvmt._Ouveture.mscx.mxl"	Done!
Encoding file #110: "String_Quartet_#2.mscx.mxl"	Done!
Encoding file #111: "String_Quartet_#5.mscx.mxl"	Done!
Encoding file #112: "String_Quartet_#5_1.mscx.mxl"	Done!
Encoding file #113: "string_quartet_1.mscx.mxl"	Done!
Encoding file #114: "String_Quartet_10.mscx.mxl"	Done!
Encoding 

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 7 P2


Done!
Encoding file #123: "String_Quartet_19.mscx.mxl"	Done!
Encoding file #124: "string_quartet_1_1.mscx.mxl"	Done!
Encoding file #125: "String_Quartet_2 A2.mscx.mxl"	Done!
Encoding file #126: "String_Quartet_20.mscx.mxl"	Done!
Encoding file #127: "String_Quartet_21.mscx.mxl"	Done!
Encoding file #128: "String_Quartet_22.mscx.mxl"	Done!
Encoding file #129: "String_Quartet_23.mscx.mxl"	Done!
Encoding file #130: "String_Quartet_24.mscx.mxl"	Done!
Encoding file #131: "string_quartet_27.mscx.mxl"	Done!
Encoding file #132: "String_Quartet_4.mscx.mxl"	Done!
Encoding file #133: "String_Quartet_4_1.mscx.mxl"	Done!
Encoding file #134: "String_Quartet_5.mscx.mxl"	Done!
Encoding file #135: "String_Quartet_6.mscx.mxl"	Done!
Encoding file #136: "String_Quartet_7.mscx.mxl"	Done!
Encoding file #137: "String_Quartet_8.mscx.mxl"	Done!
Encoding file #138: "String_Quartet_9.mscx.mxl"	Done!
Encoding file #139: "String_Quartet_activity.mscx.mxl"	Done!
Encoding file #140: "string_quartet_bird_song.mscx.mxl"

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 47 P1


Done!
Encoding file #192: "String_Quartet_No._12_1.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 47 P1


Done!
Encoding file #193: "String_Quartet_No._1Mvt2.mscx.mxl"	Done!
Encoding file #194: "String_Quartet_No._1_1.mscx.mxl"	Done!
Encoding file #195: "String_Quartet_No._1_10.mscx.mxl"	Done!
Encoding file #196: "String_Quartet_No._1_11.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 221 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 378 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 379 P2


Done!
Encoding file #197: "String_Quartet_no._1_12.mscx.mxl"	Done!
Encoding file #198: "String_Quartet_No._1_13.mscx.mxl"	Done!
Encoding file #199: "String_Quartet_No._1_14.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 221 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 378 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 379 P2


Done!
Encoding file #200: "String_Quartet_no._1_2.mscx.mxl"	Done!
Encoding file #201: "String_Quartet_No._1_3.mscx.mxl"	Done!
Encoding file #202: "String_Quartet_No._1_4.mscx.mxl"	Done!
Encoding file #203: "String_Quartet_No._1_5.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 221 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 378 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 379 P2


Done!
Encoding file #204: "String_Quartet_No._1_6.mscx.mxl"	Done!
Encoding file #205: "String_Quartet_No._1_7.mscx.mxl"	Done!
Encoding file #206: "String_Quartet_No._1_8.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 221 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 378 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 379 P2


Done!
Encoding file #207: "String_Quartet_No._1_9.mscx.mxl"	Done!
Encoding file #208: "String_Quartet_No._1_in_B_Minor.mscx.mxl"	Done!
Encoding file #209: "String_Quartet_No._1_in_D_Major.mscx.mxl"	Done!
Encoding file #210: "String_Quartet_No._1_in_D_Minor Mvt 1.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 75 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 82 P1


Done!
Encoding file #211: "String_Quartet_No._1_in_D_Minor Mvt 1_1.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 75 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 82 P1


Done!
Encoding file #212: "String_Quartet_No._1_in_D_Minor Mvt 1_2.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 75 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 82 P1


Done!
Encoding file #213: "String_Quartet_No._1_in_D_Minor Mvt 1_3.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 75 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 82 P1


Done!
Encoding file #214: "String_Quartet_No._1_in_F_major.mscx.mxl"	Done!
Encoding file #215: "String_quartet_no._2.mscx.mxl"	Done!
Encoding file #216: "String_Quartet_No._20.mscx.mxl"	Done!
Encoding file #217: "String_Quartet_No._20_1.mscx.mxl"	Done!
Encoding file #218: "String_Quartet_No._2_Prelude.mscx.mxl"	Done!
Encoding file #219: "String_Quartet_No1.mscx.mxl"	Done!
Encoding file #220: "String_Quartet_No1_in_Eb_Minor.mscx.mxl"	Done!
Encoding file #221: "String_Quartet_No2.mscx.mxl"	Done!
Encoding file #222: "String_Quartet_No2_1.mscx.mxl"	Done!
Encoding file #223: "String_Quartet_No_1.mscx.mxl"	Done!
Encoding file #224: "String_Quartet_No_1_1.mscx.mxl"	Done!
Encoding file #225: "String_Quartet_Number.1.mscx.mxl"	Done!
Encoding file #226: "String_quartet_N°2_II.mscx.mxl"	Done!
Encoding file #227: "String_quartet_N°2_III.mscx.mxl"	Done!
Encoding file #228: "String_quartet_N°2_III_1.mscx.mxl"	Done!
Encoding file #229: "String_quartet_N°2_II_1.mscx.mxl"	Done!
Encoding file #230: "Str

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 89 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 93 P2


Done!
Encoding file #440: "temp_12080_1.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 89 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 93 P2


Done!
Encoding file #441: "temp_12096.mscx.mxl"	Done!
Encoding file #442: "temp_121.mscx.mxl"	Done!
Encoding file #443: "temp_12108.mscx.mxl"	Done!
Encoding file #444: "temp_12108_1.mscx.mxl"	Done!
Encoding file #445: "temp_1212.mscx.mxl"	Done!
Encoding file #446: "temp_122.mscx.mxl"	Done!
Encoding file #447: "temp_12283.mscx.mxl"	Done!
Encoding file #448: "temp_12283_1.mscx.mxl"	Done!
Encoding file #449: "temp_123.mscx.mxl"	Done!
Encoding file #450: "temp_1231.mscx.mxl"	Done!
Encoding file #451: "temp_12347.mscx.mxl"	Done!
Encoding file #452: "temp_12382.mscx.mxl"	Done!
Encoding file #453: "temp_12382_1.mscx.mxl"	Done!
Encoding file #454: "temp_124.mscx.mxl"	Done!
Encoding file #455: "temp_1246.mscx.mxl"	Done!
Encoding file #456: "temp_12485.mscx.mxl"	Done!
Encoding file #457: "temp_125.mscx.mxl"	Done!
Encoding file #458: "temp_12505.mscx.mxl"	Done!
Encoding file #459: "temp_12538.mscx.mxl"	Done!
Encoding file #460: "temp_12566.mscx.mxl"	Done!
Encoding file #461: "temp_12578.mscx.mxl"

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 13 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 13 P2


Done!
Encoding file #637: "temp_16189.mscx.mxl"	Done!
Encoding file #638: "temp_16243.mscx.mxl"	Done!
Encoding file #639: "temp_16247.mscx.mxl"	Done!
Encoding file #640: "temp_16251.mscx.mxl"	Done!
Encoding file #641: "temp_163.mscx.mxl"	Done!
Encoding file #642: "temp_164.mscx.mxl"	Done!
Encoding file #643: "temp_16440.mscx.mxl"	Done!
Encoding file #644: "temp_16440_1.mscx.mxl"	Done!
Encoding file #645: "temp_165.mscx.mxl"	Done!
Encoding file #646: "temp_16525.mscx.mxl"	Done!
Encoding file #647: "temp_1658.mscx.mxl"	Done!
Encoding file #648: "temp_166.mscx.mxl"	Done!
Encoding file #649: "temp_16641.mscx.mxl"	Done!
Encoding file #650: "temp_16672.mscx.mxl"	Done!
Encoding file #651: "temp_167.mscx.mxl"	Done!
Encoding file #652: "temp_16709.mscx.mxl"	Done!
Encoding file #653: "temp_168.mscx.mxl"	Done!
Encoding file #654: "temp_16807.mscx.mxl"	Done!
Encoding file #655: "temp_16807_1.mscx.mxl"	Done!
Encoding file #656: "temp_16807_10.mscx.mxl"	Done!
Encoding file #657: "temp_16807_11.mscx.

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 33 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 38 P1


Done!
Encoding file #729: "temp_1762.mscx.mxl"	Done!
Encoding file #730: "temp_1762_1.mscx.mxl"	Done!
Encoding file #731: "temp_1767.mscx.mxl"	Done!
Encoding file #732: "temp_177.mscx.mxl"	Done!
Encoding file #733: "temp_17709.mscx.mxl"	Done!
Encoding file #734: "temp_17734.mscx.mxl"	Done!
Encoding file #735: "temp_17789.mscx.mxl"	Done!
Encoding file #736: "temp_17789_1.mscx.mxl"	Done!
Encoding file #737: "temp_17793.mscx.mxl"	Done!
Encoding file #738: "temp_17836.mscx.mxl"	Done!
Encoding file #739: "temp_17836_1.mscx.mxl"	Done!
Encoding file #740: "temp_17873.mscx.mxl"	Done!
Encoding file #741: "temp_17873_1.mscx.mxl"	Done!
Encoding file #742: "temp_179.mscx.mxl"	Done!
Encoding file #743: "temp_17972.mscx.mxl"	Done!
Encoding file #744: "temp_17972_1.mscx.mxl"	Done!
Encoding file #745: "temp_18.mscx.mxl"	Done!
Encoding file #746: "temp_180.mscx.mxl"	Done!
Encoding file #747: "temp_18028.mscx.mxl"	Done!
Encoding file #748: "temp_18047.mscx.mxl"	Done!
Encoding file #749: "temp_181.mscx.m

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 3 P2


Done!
Encoding file #1079: "temp_24464.mscx.mxl"	Done!
Encoding file #1080: "temp_24464_1.mscx.mxl"	Done!
Encoding file #1081: "temp_24464_2.mscx.mxl"	Done!
Encoding file #1082: "temp_24464_3.mscx.mxl"	Done!
Encoding file #1083: "temp_24498.mscx.mxl"	Done!
Encoding file #1084: "temp_24500.mscx.mxl"	Done!
Encoding file #1085: "temp_2452.mscx.mxl"	Done!
Encoding file #1086: "temp_24529.mscx.mxl"	Done!
Encoding file #1087: "temp_24588.mscx.mxl"	Done!
Encoding file #1088: "temp_246.mscx.mxl"	Done!
Encoding file #1089: "temp_24614.mscx.mxl"	Done!
Encoding file #1090: "temp_24634.mscx.mxl"	Done!
Encoding file #1091: "temp_24634_1.mscx.mxl"	Done!
Encoding file #1092: "temp_24637.mscx.mxl"	Done!
Encoding file #1093: "temp_24676.mscx.mxl"	Done!
Encoding file #1094: "temp_247.mscx.mxl"	Done!
Encoding file #1095: "temp_24710.mscx.mxl"	Done!
Encoding file #1096: "temp_24746.mscx.mxl"	Done!
Encoding file #1097: "temp_24751.mscx.mxl"	Done!
Encoding file #1098: "temp_24845.mscx.mxl"	Done!
Encoding fi

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 19 P1


Done!
Encoding file #1176: "temp_26500_5.mscx.mxl"	Done!
Encoding file #1177: "temp_26500_6.mscx.mxl"	Done!
Encoding file #1178: "temp_26500_7.mscx.mxl"	Done!
Encoding file #1179: "temp_26500_8.mscx.mxl"	Done!
Encoding file #1180: "temp_26500_9.mscx.mxl"	Done!
Encoding file #1181: "temp_26509.mscx.mxl"	Done!
Encoding file #1182: "temp_266.mscx.mxl"	Done!
Encoding file #1183: "temp_26603.mscx.mxl"	Done!
Encoding file #1184: "temp_26650.mscx.mxl"	Done!
Encoding file #1185: "temp_26684.mscx.mxl"	Done!
Encoding file #1186: "temp_26686.mscx.mxl"	Done!
Encoding file #1187: "temp_267.mscx.mxl"	Done!
Encoding file #1188: "temp_26703.mscx.mxl"	Done!
Encoding file #1189: "temp_26718.mscx.mxl"	Done!
Encoding file #1190: "temp_26756.mscx.mxl"	Done!
Encoding file #1191: "temp_26756_1.mscx.mxl"	Done!
Encoding file #1192: "temp_26768.mscx.mxl"	Done!
Encoding file #1193: "temp_268.mscx.mxl"	Done!
Encoding file #1194: "temp_26810.mscx.mxl"	Done!
Encoding file #1195: "temp_26880.mscx.mxl"	Done!
Encoding

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 3 P1


Done!
Encoding file #1276: "temp_27869.mscx.mxl"	Done!
Encoding file #1277: "temp_27869_1.mscx.mxl"	Done!
Encoding file #1278: "temp_27869_2.mscx.mxl"	Done!
Encoding file #1279: "temp_27894.mscx.mxl"	Done!
Encoding file #1280: "temp_279.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 3 P1
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 5 P4


Done!
Encoding file #1281: "temp_27919.mscx.mxl"	Done!
Encoding file #1282: "temp_27924.mscx.mxl"	Done!
Encoding file #1283: "temp_27924_1.mscx.mxl"	Done!
Encoding file #1284: "temp_27972.mscx.mxl"	Done!
Encoding file #1285: "temp_27972_1.mscx.mxl"	Done!
Encoding file #1286: "temp_28.mscx.mxl"	Done!
Encoding file #1287: "temp_280.mscx.mxl"	Done!
Encoding file #1288: "temp_281.mscx.mxl"	Done!
Encoding file #1289: "temp_2812.mscx.mxl"	Done!
Encoding file #1290: "temp_28134.mscx.mxl"	Done!
Encoding file #1291: "temp_28137.mscx.mxl"	Done!
Encoding file #1292: "temp_28145.mscx.mxl"	Done!
Encoding file #1293: "temp_28146.mscx.mxl"	Done!
Encoding file #1294: "temp_28146_1.mscx.mxl"	Done!
Encoding file #1295: "temp_282.mscx.mxl"	Done!
Encoding file #1296: "temp_28200.mscx.mxl"	Done!
Encoding file #1297: "temp_28200_1.mscx.mxl"	Done!
Encoding file #1298: "temp_28218.mscx.mxl"	Done!
Encoding file #1299: "temp_28218_1.mscx.mxl"	Done!
Encoding file #1300: "temp_28241.mscx.mxl"	Done!
Encoding file 

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 35 P3


Done!
Encoding file #1310: "temp_28475.mscx.mxl"	Done!
Encoding file #1311: "temp_285.mscx.mxl"	Done!
Encoding file #1312: "temp_28504.mscx.mxl"	Done!
Encoding file #1313: "temp_28597.mscx.mxl"	Done!
Encoding file #1314: "temp_28597_1.mscx.mxl"	Done!
Encoding file #1315: "temp_286.mscx.mxl"	Done!
Encoding file #1316: "temp_28654.mscx.mxl"	Done!
Encoding file #1317: "temp_28670.mscx.mxl"	Done!
Encoding file #1318: "temp_287.mscx.mxl"	Done!
Encoding file #1319: "temp_28700.mscx.mxl"	Done!
Encoding file #1320: "temp_28703.mscx.mxl"	Done!
Encoding file #1321: "temp_28753.mscx.mxl"	Done!
Encoding file #1322: "temp_28764.mscx.mxl"	Done!
Encoding file #1323: "temp_2879.mscx.mxl"	Done!
Encoding file #1324: "temp_28797.mscx.mxl"	Done!
Encoding file #1325: "temp_2879_1.mscx.mxl"	Done!
Encoding file #1326: "temp_288.mscx.mxl"	Done!
Encoding file #1327: "temp_28817.mscx.mxl"	Done!
Encoding file #1328: "temp_28829.mscx.mxl"	Done!
Encoding file #1329: "temp_28829_1.mscx.mxl"	Done!
Encoding file #133

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 24 P3


Done!
Encoding file #1408: "temp_302.mscx.mxl"	Done!
Encoding file #1409: "temp_30218.mscx.mxl"	Done!
Encoding file #1410: "temp_30255.mscx.mxl"	Done!
Encoding file #1411: "temp_303.mscx.mxl"	Done!
Encoding file #1412: "temp_30302.mscx.mxl"	Done!
Encoding file #1413: "temp_304.mscx.mxl"	Done!
Encoding file #1414: "temp_30432.mscx.mxl"	Done!
Encoding file #1415: "temp_30444.mscx.mxl"	Done!
Encoding file #1416: "temp_30481.mscx.mxl"	Done!
Encoding file #1417: "temp_30482.mscx.mxl"	Done!
Encoding file #1418: "temp_30482_1.mscx.mxl"	Done!
Encoding file #1419: "temp_30499.mscx.mxl"	Done!
Encoding file #1420: "temp_305.mscx.mxl"	Done!
Encoding file #1421: "temp_306.mscx.mxl"	Done!
Encoding file #1422: "temp_30640.mscx.mxl"	Done!
Encoding file #1423: "temp_30640_1.mscx.mxl"	Done!
Encoding file #1424: "temp_30674.mscx.mxl"	Done!
Encoding file #1425: "temp_30681.mscx.mxl"	Done!
Encoding file #1426: "temp_307.mscx.mxl"	Done!
Encoding file #1427: "temp_30778.mscx.mxl"	Done!
Encoding file #1428: "

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 89 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 93 P2


Done!
Encoding file #1639: "temp_3997_1.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 89 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 93 P2


Done!
Encoding file #1640: "temp_4.mscx.mxl"	Done!
Encoding file #1641: "temp_40.mscx.mxl"	Done!
Encoding file #1642: "temp_400.mscx.mxl"	Done!
Encoding file #1643: "temp_401.mscx.mxl"	Done!
Encoding file #1644: "temp_4013.mscx.mxl"	Parsing error: float division by zero. Skipping...
Encoding file #1645: "temp_402.mscx.mxl"	Done!
Encoding file #1646: "temp_403.mscx.mxl"	Done!
Encoding file #1647: "temp_404.mscx.mxl"	Done!
Encoding file #1648: "temp_405.mscx.mxl"	Done!
Encoding file #1649: "temp_40651.mscx.mxl"	Done!
Encoding file #1650: "temp_40651_1.mscx.mxl"	Done!
Encoding file #1651: "temp_407.mscx.mxl"	Done!
Encoding file #1652: "temp_408.mscx.mxl"	Done!
Encoding file #1653: "temp_409.mscx.mxl"	Done!
Encoding file #1654: "temp_41.mscx.mxl"	Done!
Encoding file #1655: "temp_410.mscx.mxl"	Done!
Encoding file #1656: "temp_411.mscx.mxl"	Done!
Encoding file #1657: "temp_41139.mscx.mxl"	Done!
Encoding file #1658: "temp_412.mscx.mxl"	Done!
Encoding file #1659: "temp_41260.mscx.mxl"	Done!
En

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 7 P3
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 7 P3


Done!
Encoding file #2031: "temp_48116.mscx.mxl"	Done!
Encoding file #2032: "temp_48118.mscx.mxl"	Done!
Encoding file #2033: "temp_48130.mscx.mxl"	Done!
Encoding file #2034: "temp_48130_1.mscx.mxl"	Done!
Encoding file #2035: "temp_482.mscx.mxl"	Done!
Encoding file #2036: "temp_4827.mscx.mxl"	Done!
Encoding file #2037: "temp_48271.mscx.mxl"	Done!
Encoding file #2038: "temp_48271_1.mscx.mxl"	Done!
Encoding file #2039: "temp_48271_10.mscx.mxl"	Done!
Encoding file #2040: "temp_48271_11.mscx.mxl"	Done!
Encoding file #2041: "temp_48271_12.mscx.mxl"	Done!
Encoding file #2042: "temp_48271_13.mscx.mxl"	Done!
Encoding file #2043: "temp_48271_14.mscx.mxl"	Done!
Encoding file #2044: "temp_48271_15.mscx.mxl"	Done!
Encoding file #2045: "temp_48271_16.mscx.mxl"	Done!
Encoding file #2046: "temp_48271_17.mscx.mxl"	Done!
Encoding file #2047: "temp_48271_18.mscx.mxl"	Done!
Encoding file #2048: "temp_48271_19.mscx.mxl"	Done!
Encoding file #2049: "temp_48271_2.mscx.mxl"	Done!
Encoding file #2050: "temp_482

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 20 P2


Done!
Encoding file #2375: "temp_6334_31.mscx.mxl"	Done!
Encoding file #2376: "temp_6334_32.mscx.mxl"	Done!
Encoding file #2377: "temp_6334_33.mscx.mxl"	Done!
Encoding file #2378: "temp_6334_34.mscx.mxl"	Done!
Encoding file #2379: "temp_6334_35.mscx.mxl"	Done!
Encoding file #2380: "temp_6334_36.mscx.mxl"	Done!
Encoding file #2381: "temp_6334_37.mscx.mxl"	Done!
Encoding file #2382: "temp_6334_38.mscx.mxl"	Done!
Encoding file #2383: "temp_6334_39.mscx.mxl"	Done!
Encoding file #2384: "temp_6334_4.mscx.mxl"	Done!
Encoding file #2385: "temp_6334_40.mscx.mxl"	Done!
Encoding file #2386: "temp_6334_41.mscx.mxl"	Done!
Encoding file #2387: "temp_6334_42.mscx.mxl"	Done!
Encoding file #2388: "temp_6334_43.mscx.mxl"	Done!
Encoding file #2389: "temp_6334_44.mscx.mxl"	Done!
Encoding file #2390: "temp_6334_45.mscx.mxl"	Done!
Encoding file #2391: "temp_6334_46.mscx.mxl"	Done!
Encoding file #2392: "temp_6334_47.mscx.mxl"	Done!
Encoding file #2393: "temp_6334_48.mscx.mxl"	Done!
Encoding file #2394: "temp

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 34 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 34 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 34 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 34 P2
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 34 P2


Done!
Encoding file #2412: "temp_636.mscx.mxl"	Done!
Encoding file #2413: "temp_637.mscx.mxl"	Done!
Encoding file #2414: "temp_638.mscx.mxl"	Done!
Encoding file #2415: "temp_6391.mscx.mxl"	Done!
Encoding file #2416: "temp_6391_1.mscx.mxl"	Done!
Encoding file #2417: "temp_64.mscx.mxl"	Done!
Encoding file #2418: "temp_640.mscx.mxl"	Done!
Encoding file #2419: "temp_6409.mscx.mxl"	Done!
Encoding file #2420: "temp_6409_1.mscx.mxl"	Done!
Encoding file #2421: "temp_641.mscx.mxl"	Done!
Encoding file #2422: "temp_643.mscx.mxl"	Done!
Encoding file #2423: "temp_6431.mscx.mxl"	Done!
Encoding file #2424: "temp_6431_1.mscx.mxl"	Done!
Encoding file #2425: "temp_644.mscx.mxl"	Done!
Encoding file #2426: "temp_6441.mscx.mxl"	Done!
Encoding file #2427: "temp_6456.mscx.mxl"	Done!
Encoding file #2428: "temp_64574.mscx.mxl"	Done!
Encoding file #2429: "temp_646.mscx.mxl"	Done!
Encoding file #2430: "temp_6475.mscx.mxl"	Done!
Encoding file #2431: "temp_6475_1.mscx.mxl"	Done!
Encoding file #2432: "temp_64821.ms

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 7 P3
musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 7 P3


Done!
Encoding file #2481: "temp_681.mscx.mxl"	Done!
Encoding file #2482: "temp_682.mscx.mxl"	Done!
Encoding file #2483: "temp_683.mscx.mxl"	Done!
Encoding file #2484: "temp_684.mscx.mxl"	Done!
Encoding file #2485: "temp_68406.mscx.mxl"	Done!
Encoding file #2486: "temp_686.mscx.mxl"	Done!
Encoding file #2487: "temp_6865.mscx.mxl"	Done!
Encoding file #2488: "temp_6865_1.mscx.mxl"	Done!
Encoding file #2489: "temp_687.mscx.mxl"	Done!
Encoding file #2490: "temp_6870.mscx.mxl"	Done!
Encoding file #2491: "temp_68782.mscx.mxl"	Done!
Encoding file #2492: "temp_68782_1.mscx.mxl"	Done!
Encoding file #2493: "temp_689.mscx.mxl"	Done!
Encoding file #2494: "temp_68903.mscx.mxl"	Done!
Encoding file #2495: "temp_69.mscx.mxl"	Done!
Encoding file #2496: "temp_690.mscx.mxl"	Done!
Encoding file #2497: "temp_69041.mscx.mxl"	Done!
Encoding file #2498: "temp_69041_1.mscx.mxl"	Done!
Encoding file #2499: "temp_69041_2.mscx.mxl"	Done!
Encoding file #2500: "temp_69041_3.mscx.mxl"	Done!
Encoding file #2501: "temp

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 7 P4


Done!
Encoding file #2509: "temp_69386.mscx.mxl"	Done!
Encoding file #2510: "temp_694.mscx.mxl"	Done!
Encoding file #2511: "temp_6954.mscx.mxl"	Done!
Encoding file #2512: "temp_6954_1.mscx.mxl"	Done!
Encoding file #2513: "temp_698.mscx.mxl"	Done!
Encoding file #2514: "temp_7.mscx.mxl"	Done!
Encoding file #2515: "temp_70.mscx.mxl"	Done!
Encoding file #2516: "temp_701.mscx.mxl"	Done!
Encoding file #2517: "temp_7011.mscx.mxl"	Done!
Encoding file #2518: "temp_704.mscx.mxl"	Done!
Encoding file #2519: "temp_70408.mscx.mxl"	Done!
Encoding file #2520: "temp_70441.mscx.mxl"	Done!
Encoding file #2521: "temp_705.mscx.mxl"	Done!
Encoding file #2522: "temp_7057.mscx.mxl"	Done!
Encoding file #2523: "temp_707.mscx.mxl"	Done!
Encoding file #2524: "temp_7070.mscx.mxl"	Done!
Encoding file #2525: "temp_708.mscx.mxl"	Done!
Encoding file #2526: "temp_7080.mscx.mxl"	Done!
Encoding file #2527: "temp_709.mscx.mxl"	Parsing error: float division by zero. Skipping...
Encoding file #2528: "temp_71.mscx.mxl"	Done!

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 6 P1


Done!
Encoding file #2535: "temp_71494.mscx.mxl"	Done!
Encoding file #2536: "temp_715.mscx.mxl"	Done!
Encoding file #2537: "temp_717.mscx.mxl"	Done!
Encoding file #2538: "temp_717_1.mscx.mxl"	Done!
Encoding file #2539: "temp_718.mscx.mxl"	Done!
Encoding file #2540: "temp_72.mscx.mxl"	Done!
Encoding file #2541: "temp_720.mscx.mxl"	Done!
Encoding file #2542: "temp_72051.mscx.mxl"	Done!
Encoding file #2543: "temp_721.mscx.mxl"	Done!
Encoding file #2544: "temp_722.mscx.mxl"	Done!
Encoding file #2545: "temp_723.mscx.mxl"	Done!
Encoding file #2546: "temp_724.mscx.mxl"	Done!
Encoding file #2547: "temp_725.mscx.mxl"	Done!
Encoding file #2548: "temp_73.mscx.mxl"	Done!
Encoding file #2549: "temp_730.mscx.mxl"	Done!
Encoding file #2550: "temp_7312.mscx.mxl"	Done!
Encoding file #2551: "temp_7312_1.mscx.mxl"	Done!
Encoding file #2552: "temp_7314.mscx.mxl"	Done!
Encoding file #2553: "temp_7321.mscx.mxl"	Done!
Encoding file #2554: "temp_7321_1.mscx.mxl"	Done!
Encoding file #2555: "temp_734.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 33 P1


Done!
Encoding file #2666: "temp_84492_1.mscx.mxl"	Done!
Encoding file #2667: "temp_84492_2.mscx.mxl"	Done!
Encoding file #2668: "temp_84492_3.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 33 P1


Done!
Encoding file #2669: "temp_84527.mscx.mxl"	Done!
Encoding file #2670: "temp_84678.mscx.mxl"	Done!
Encoding file #2671: "temp_8493.mscx.mxl"	Done!
Encoding file #2672: "temp_85.mscx.mxl"	Done!
Encoding file #2673: "temp_8502.mscx.mxl"	Done!
Encoding file #2674: "temp_85300.mscx.mxl"	Done!
Encoding file #2675: "temp_85300_1.mscx.mxl"	Done!
Encoding file #2676: "temp_85544.mscx.mxl"	Done!
Encoding file #2677: "temp_85544_1.mscx.mxl"	Done!
Encoding file #2678: "temp_85606.mscx.mxl"	Done!
Encoding file #2679: "temp_85722.mscx.mxl"	Done!
Encoding file #2680: "temp_85785.mscx.mxl"	Done!
Encoding file #2681: "temp_85843.mscx.mxl"	Done!
Encoding file #2682: "temp_85944.mscx.mxl"	Done!
Encoding file #2683: "temp_86.mscx.mxl"	Done!
Encoding file #2684: "temp_8604.mscx.mxl"	Done!
Encoding file #2685: "temp_8604_1.mscx.mxl"	Done!
Encoding file #2686: "temp_86349.mscx.mxl"	Done!
Encoding file #2687: "temp_8639.mscx.mxl"	Done!
Encoding file #2688: "temp_8639_1.mscx.mxl"	Done!
Encoding file #268

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 31 P2


Done!
Encoding file #2695: "temp_8708_1.mscx.mxl"	

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 31 P2


Done!
Encoding file #2696: "temp_87207.mscx.mxl"	Done!
Encoding file #2697: "temp_8762.mscx.mxl"	Done!
Encoding file #2698: "temp_87756.mscx.mxl"	Done!
Encoding file #2699: "temp_88.mscx.mxl"	Done!
Encoding file #2700: "temp_880.mscx.mxl"	Done!
Encoding file #2701: "temp_882.mscx.mxl"	Done!
Encoding file #2702: "temp_8824.mscx.mxl"	Done!
Encoding file #2703: "temp_8824_1.mscx.mxl"	Done!
Encoding file #2704: "temp_8853.mscx.mxl"	Done!
Encoding file #2705: "temp_8874.mscx.mxl"	Parsing error: float division by zero. Skipping...
Encoding file #2706: "temp_8892.mscx.mxl"	Done!
Encoding file #2707: "temp_89.mscx.mxl"	Done!
Encoding file #2708: "temp_89231.mscx.mxl"	Done!
Encoding file #2709: "temp_8930.mscx.mxl"	Done!
Encoding file #2710: "temp_89300.mscx.mxl"	Done!
Encoding file #2711: "temp_8930_10.mscx.mxl"	Done!
Encoding file #2712: "temp_8930_11.mscx.mxl"	Done!
Encoding file #2713: "temp_8930_12.mscx.mxl"	Done!
Encoding file #2714: "temp_8930_13.mscx.mxl"	Done!
Encoding file #2715: "tem

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 16 P2


Done!
Encoding file #2952: "The_twelve.mxl"	Done!
Encoding file #2953: "The_Ultimate_Sacrifice.mxl"	Done!
Encoding file #2954: "The_Ultimate_Sacrifice_1.mxl"	Done!
Encoding file #2955: "The_Witch's_Hymn.mxl"	Done!
Encoding file #2956: "The_world_revolving_Score.mxl"	Done!
Encoding file #2957: "Thinking_Music.mxl"	Done!
Encoding file #2958: "Thinking_out_Loud.mxl"	Done!
Encoding file #2959: "This is terrible.mxl"	Done!
Encoding file #2960: "This_Is_Where_I_Fall(uploaded).mxl"	Done!
Encoding file #2961: "Throne_Room.mxl"	Done!
Encoding file #2962: "THX String Quartet.mxl"	Done!
Encoding file #2963: "THX String Quartet_1.mxl"	Done!
Encoding file #2964: "Thy Word.mxl"	Done!
Encoding file #2965: "Tibutab.mxl"	Done!
Encoding file #2966: "Tidecaller updated score.mxl"	Done!
Encoding file #2967: "Tidecaller updated score_1.mxl"	Done!
Encoding file #2968: "Tik_un_tā.mxl"	Done!
Encoding file #2969: "Time's Scar - Chrono Cross Game Opening.mxl"	Done!
Encoding file #2970: "Time's Scar - Chrono Cro

musicxml.xmlToM21: WARNING: Could not import wedge: Error in getting DynamicWedges...Measure no. 16 P1


Done!
Encoding file #3167: "Yankee_Doodle_Boy.mxl"	Done!
Encoding file #3168: "Yee.mxl"	Done!
Encoding file #3169: "Yorubaland Fantasy.mxl"	Done!
Encoding file #3170: "Young composers 2016 Entry String Quartet Ensemble Entry .mxl"	Done!
Encoding file #3171: "Youngblood (String Mix).mxl"	Done!
Encoding file #3172: "Your Song.mxl"	Done!
Encoding file #3173: "You_and_Me.mxl"	Done!
Encoding file #3174: "You_and_Me_1.mxl"	Done!
Encoding file #3175: "You_are_the_reason_-_Duet.mxl"	Done!
Encoding file #3176: "You_better_save_me_bc_I'm_dyin'.mxl"	Done!
Encoding file #3177: "You_Will_Be_Found.mxl"	Done!
Encoding file #3178: "You_Will_Be_Found_1.mxl"	Done!
Encoding file #3179: "You_Will_Be_Found_2.mxl"	Done!
Encoding file #3180: "You_Will_Be_Found_3.mxl"	Done!
Encoding file #3181: "Yume To Hazakura (Strings).mxl"	Done!
Encoding file #3182: "Z-World_strings.mxl"	Done!
Encoding file #3183: "Z-World_strings_1.mxl"	Done!
Encoding file #3184: "Zelda Title Thme v1.1.mxl"	Done!
Encoding file #3185: "Ze

In [264]:
import sys


sys.path.insert(1, '../')

In [265]:
import lib_pianoroll

In [266]:
from collections import namedtuple


HParam = namedtuple('HParam', ['shortest_duration', 'min_pitch', 'max_pitch', 'separate_instruments', 'num_instruments', 'quantization_level'])

hparam = HParam(
    shortest_duration=0.125,
    min_pitch=36,
    max_pitch=81,
    separate_instruments=True,
    num_instruments=4,
    quantization_level=None)

encoder = lib_pianoroll.get_pianoroll_encoder_decoder(hparam)

In [267]:
import pretty_midi


test_midi = pretty_midi.PrettyMIDI("../data/midis/3. What's This.mscx.mxl.midi")

/root/anaconda3/envs/magenta/lib/python3.8/site-packages/pretty_midi/pretty_midi.py:97: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  warnings.warn(


In [268]:
test_midi.instruments

[Instrument(program=40, is_drum=False, name="Violin I"),
 Instrument(program=40, is_drum=False, name="Violin II"),
 Instrument(program=41, is_drum=False, name="Viola"),
 Instrument(program=42, is_drum=False, name="Violoncello")]

In [269]:
import numpy as np

bach_data = np.load('../JSB-Chorales-dataset-master/Jsb16thSeparated.npz', allow_pickle=True, encoding='latin1')


In [270]:
[key for key in bach_data.keys()]

['test', 'train', 'valid']

In [271]:
bach_data['train'][0].shape

(192, 4)

In [272]:
bach_data['train']

array([array([[74., 70., 65., 58.],
       [74., 70., 65., 58.],
       [74., 70., 65., 58.],
       [74., 70., 65., 58.],
       [75., 70., 58., 55.],
       [75., 70., 58., 55.],
       [75., 70., 60., 55.],
       [75., 70., 60., 55.],
       [77., 69., 62., 50.],
       [77., 69., 62., 50.],
       [77., 69., 62., 50.],
       [77., 69., 62., 50.],
       [77., 70., 62., 55.],
       [77., 70., 62., 55.],
       [77., 69., 62., 55.],
       [77., 69., 62., 55.],
       [75., 67., 63., 48.],
       [75., 67., 63., 48.],
       [75., 69., 63., 48.],
       [75., 69., 63., 48.],
       [74., 70., 65., 46.],
       [74., 70., 65., 46.],
       [74., 70., 65., 46.],
       [74., 70., 65., 46.],
       [72., 69., 65., 53.],
       [72., 69., 65., 53.],
       [72., 69., 65., 53.],
       [72., 69., 65., 53.],
       [72., 69., 65., 53.],
       [72., 69., 65., 53.],
       [72., 69., 65., 53.],
       [72., 69., 65., 53.],
       [74., 70., 65., 46.],
       [74., 70., 65., 46.],
       

In [273]:
[array.shape for array in bach_data['train']]

[(192, 4),
 (228, 4),
 (208, 4),
 (432, 4),
 (260, 4),
 (212, 4),
 (292, 4),
 (180, 4),
 (132, 4),
 (192, 4),
 (208, 4),
 (272, 4),
 (260, 4),
 (132, 4),
 (196, 4),
 (456, 4),
 (208, 4),
 (452, 4),
 (352, 4),
 (196, 4),
 (196, 4),
 (224, 4),
 (196, 4),
 (384, 4),
 (196, 4),
 (392, 4),
 (212, 4),
 (212, 4),
 (164, 4),
 (196, 4),
 (176, 4),
 (132, 4),
 (180, 4),
 (100, 4),
 (232, 4),
 (260, 4),
 (224, 4),
 (160, 4),
 (308, 4),
 (260, 4),
 (228, 4),
 (340, 4),
 (192, 4),
 (332, 4),
 (372, 4),
 (304, 4),
 (336, 4),
 (240, 4),
 (208, 4),
 (148, 4),
 (404, 4),
 (244, 4),
 (228, 4),
 (132, 4),
 (132, 4),
 (272, 4),
 (260, 4),
 (260, 4),
 (276, 4),
 (132, 4),
 (260, 4),
 (196, 4),
 (196, 4),
 (228, 4),
 (180, 4),
 (228, 4),
 (192, 4),
 (156, 4),
 (196, 4),
 (228, 4),
 (432, 4),
 (132, 4),
 (336, 4),
 (304, 4),
 (164, 4),
 (516, 4),
 (228, 4),
 (192, 4),
 (132, 4),
 (240, 4),
 (208, 4),
 (228, 4),
 (244, 4),
 (260, 4),
 (260, 4),
 (304, 4),
 (132, 4),
 (420, 4),
 (228, 4),
 (164, 4),
 (328, 4),

In [274]:
# bb, tt, pp, ii = requested_shape


# tt = length of midi sequence based on shortest duration

# ii = num of the instruments, column # of inner array

In [275]:
test_midi.time_signature_changes

[TimeSignature(numerator=2, denominator=4, time=0.0),
 TimeSignature(numerator=3, denominator=4, time=3.0),
 TimeSignature(numerator=2, denominator=4, time=9.75),
 TimeSignature(numerator=3, denominator=4, time=18.75),
 TimeSignature(numerator=2, denominator=4, time=34.5),
 TimeSignature(numerator=3, denominator=4, time=40.5),
 TimeSignature(numerator=2, denominator=4, time=47.25),
 TimeSignature(numerator=3, denominator=4, time=68.25),
 TimeSignature(numerator=2, denominator=4, time=75.0),
 TimeSignature(numerator=3, denominator=4, time=81.0),
 TimeSignature(numerator=2, denominator=4, time=87.75),
 TimeSignature(numerator=3, denominator=4, time=99.75),
 TimeSignature(numerator=2, denominator=4, time=106.5),
 TimeSignature(numerator=3, denominator=4, time=127.5),
 TimeSignature(numerator=2, denominator=4, time=134.25)]

In [276]:
(test_denominator, test_numerator) = (test_midi.time_signature_changes[0].denominator, test_midi.time_signature_changes[0].numerator)
test_denominator, test_numerator

(4, 2)

In [277]:
test_16_factor = test_numerator / test_denominator * 16
test_16_factor

8.0

In [278]:
test_midi.get_tempo_changes()

(array([0.]), array([80.]))

In [279]:
test_midi.get_beats()

array([  0.  ,   0.75,   1.5 ,   2.25,   3.  ,   3.75,   4.5 ,   5.25,
         6.  ,   6.75,   7.5 ,   8.25,   9.  ,   9.75,  10.5 ,  11.25,
        12.  ,  12.75,  13.5 ,  14.25,  15.  ,  15.75,  16.5 ,  17.25,
        18.  ,  18.75,  19.5 ,  20.25,  21.  ,  21.75,  22.5 ,  23.25,
        24.  ,  24.75,  25.5 ,  26.25,  27.  ,  27.75,  28.5 ,  29.25,
        30.  ,  30.75,  31.5 ,  32.25,  33.  ,  33.75,  34.5 ,  35.25,
        36.  ,  36.75,  37.5 ,  38.25,  39.  ,  39.75,  40.5 ,  41.25,
        42.  ,  42.75,  43.5 ,  44.25,  45.  ,  45.75,  46.5 ,  47.25,
        48.  ,  48.75,  49.5 ,  50.25,  51.  ,  51.75,  52.5 ,  53.25,
        54.  ,  54.75,  55.5 ,  56.25,  57.  ,  57.75,  58.5 ,  59.25,
        60.  ,  60.75,  61.5 ,  62.25,  63.  ,  63.75,  64.5 ,  65.25,
        66.  ,  66.75,  67.5 ,  68.25,  69.  ,  69.75,  70.5 ,  71.25,
        72.  ,  72.75,  73.5 ,  74.25,  75.  ,  75.75,  76.5 ,  77.25,
        78.  ,  78.75,  79.5 ,  80.25,  81.  ,  81.75,  82.5 ,  83.25,
      

In [280]:
test_16th = test_midi.get_downbeats()[1] / test_16_factor
test_16th

0.1875

In [281]:
test_pianoroll = [array for array in test_midi.instruments[0].get_piano_roll(fs=(1.0/test_16th))]

np.argmax(test_midi.instruments[0].get_piano_roll(fs=(1.0/test_16th)), axis=0)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 74, 77,
        0,  0, 62, 65,  0,  0, 74, 77, 79, 81, 82, 81,  0,  0, 61, 61,  0,
        0, 73, 76, 77, 79, 81, 77,  0,  0, 62, 65,  0,  0, 74, 77, 79, 81,
       82, 81,  0,  0, 77, 81,  0,  0, 77, 81, 77, 79, 76, 74, 74, 86, 86,
       84, 84, 84, 84, 81, 81, 77, 77, 70, 74, 77, 82, 86, 86, 86, 86, 82,
       82, 79, 76, 73, 73, 70, 70, 69, 69, 69, 70, 72, 72, 72, 72,  0,  0,
       82, 84, 86, 86, 86, 86, 86, 86, 84, 84, 87, 87, 87, 87, 82, 82, 79,
       79, 77, 74, 71, 67, 72, 72, 72, 72, 72, 69, 66, 66, 63, 63, 60, 60,
       59, 59, 59, 59, 59, 59, 59, 59,  0,  0,  0, 63, 67,  0,  0, 64, 67,
        0,  0, 64, 67, 69, 71, 72, 71,  0,  0, 63, 66,  0,  0, 63, 66, 67,
       69, 71, 67,  0,  0, 64, 67,  0,  0, 64, 67, 69, 71, 72, 71, 67, 71,
       67, 71, 67, 71, 67, 71, 67, 71, 67, 71, 71,  0, 71, 72, 72,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 64, 67,  0,  0, 64, 67,
        0,  0, 64, 67, 69

In [282]:
def gen_piano_roll(file_path):
    midi = pretty_midi.PrettyMIDI(file_path)
    (denominator, numerator) = (midi.time_signature_changes[0].denominator, midi.time_signature_changes[0].numerator)
    sixteenth_factor = numerator / denominator * 16
    sixteenth_length = midi.get_downbeats()[1] / sixteenth_factor
    return np.array([
        np.argmax(midi.instruments[part_num].get_piano_roll(fs=(1.0/sixteenth_length)), axis=0) for part_num in range(4)
    ], dtype=object).T

gen_piano_roll("../data/midis/3. What's This.mscx.mxl.midi")

array([[0, 0, 65, 46],
       [0, 0, 62, 46],
       [0, 0, 65, 46],
       ...,
       [76, 73, 69, 57],
       [69, 61, 57, 45],
       [69, 61, 57, 45]], dtype=object)

In [285]:
len(os.listdir('../data/midis'))

5281

In [286]:
data_container = np.empty(len(os.listdir('../data/midis')), dtype=object)


for num, file in enumerate(os.listdir('../data/midis')):
    print(f'Converting file #{num} {file} to numpy array...', end = '\t\t')
    try:
        data_container[num] = gen_piano_roll('../data/midis/' + file)
        print('Done!')
    except Exception as e:
        print(f'Error converting: {e.__class__.__name__} - {e}, skipping...')
    

Converting file #0 !!!!!StringQuartetNo.3(3rd_Mov.).mscx.mxl.midi to numpy array...		Done!
Converting file #1 !!!!!StringQuartetNo.3(3rd_Mov.)_1.mscx.mxl.midi to numpy array...		Done!
Converting file #2 !hAyDn_CoMpOsItIon_TeChNiQuEs!.mscx.mxl.midi to numpy array...		Done!
Converting file #3 (auf_dem_Weg_nach_Stuttgart).mscx.mxl.midi to numpy array...		Done!
Converting file #4 (auf_dem_Weg_nach_Stuttgart)V2.mscx.mxl.midi to numpy array...		Done!
Converting file #5 ......mscx.mxl.midi to numpy array...		Done!
Converting file #6 ....._1.mscx.mxl.midi to numpy array...		Done!
Converting file #7 ....mscx.mxl.midi to numpy array...		Done!
Converting file #8 .Leaning on the Everlasting Arms.mscx.mxl.midi to numpy array...		Done!
Converting file #9 .Revised String Quartet in C# minor.mscx.mxl.midi to numpy array...		Done!
Converting file #10 .Revised String Quartet in C# minor_1.mscx.mxl.midi to numpy array...		Done!
Converting file #11 0)19str_2020June6.mscx.mxl.midi to numpy array...		Done!


In [251]:
bach_data['train'].shape

(229,)

In [253]:
bach_data['test'].shape

(77,)

In [254]:
bach_data['valid'].shape

(76,)

In [255]:
77 / (77 + 76 + 229)

0.20157068062827224

In [291]:
data_container

array([array([[0, 0, 48, 36],
       [0, 0, 48, 36],
       [0, 0, 0, 0],
       ...,
       [72, 60, 48, 36],
       [0, 0, 0, 0],
       [72, 60, 48, 36]], dtype=object),
       array([[0, 0, 48, 36],
       [0, 0, 48, 36],
       [0, 0, 0, 0],
       ...,
       [72, 60, 48, 36],
       [0, 0, 0, 0],
       [72, 60, 48, 36]], dtype=object),
       array([array([74, 74, 75, 75, 63, 63, 63, 63, 63, 63, 63, 63, 74, 74, 75, 75, 65,
       65, 65, 65, 65, 65, 65, 65, 71, 71, 72, 72, 65, 65, 65, 65, 65, 65,
       65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 58, 58, 58, 58,
       58, 58, 58, 58, 62, 62, 65, 65, 68, 68, 70, 70, 74, 74, 77, 77, 80,
       80, 84, 84, 84, 84, 82, 82, 80, 80, 79, 79, 77, 77, 75, 75, 70, 70,
       70, 70, 72, 72, 72, 72, 74, 74, 74, 74, 75, 75, 75, 75,  0,  0,  0,
        0, 74, 74, 84, 84, 84, 84, 82, 82, 80, 80, 79, 79, 77, 77, 74, 74,
       75, 75, 75, 75,  0,  0,  0,  0, 6

In [300]:
good_data_idx = []

for (num, array) in enumerate(data_container):
    try:
        print(f'Array #{num}, shape={array.shape}', end='; ')
        if array.ndim == 2:
            print('Great!')
            good_data_idx.append(num)
        else:
            print('Bad!!!!!!!!!!!!!!!!!!!')
            
    except AttributeError:
        print(f'Array #{num} is empty')
    

Array #0, shape=(1768, 4); Great!
Array #1, shape=(1768, 4); Great!
Array #2, shape=(4,); Bad!!!!!!!!!!!!!!!!!!!
Array #3, shape=(4,); Bad!!!!!!!!!!!!!!!!!!!
Array #4, shape=(899, 4); Great!
Array #5, shape=(320, 4); Great!
Array #6, shape=(320, 4); Great!
Array #7, shape=(4,); Bad!!!!!!!!!!!!!!!!!!!
Array #8, shape=(4,); Bad!!!!!!!!!!!!!!!!!!!
Array #9, shape=(2376, 4); Great!
Array #10, shape=(2376, 4); Great!
Array #11, shape=(8765, 4); Great!
Array #12, shape=(8765, 4); Great!
Array #13, shape=(190, 4); Great!
Array #14, shape=(1216, 4); Great!
Array #15, shape=(634, 4); Great!
Array #16, shape=(634, 4); Great!
Array #17 is empty
Array #18 is empty
Array #19, shape=(480, 4); Great!
Array #20, shape=(410, 4); Great!
Array #21, shape=(264, 4); Great!
Array #22, shape=(4,); Bad!!!!!!!!!!!!!!!!!!!
Array #23, shape=(492, 4); Great!
Array #24 is empty
Array #25, shape=(4,); Bad!!!!!!!!!!!!!!!!!!!
Array #26, shape=(96, 4); Great!
Array #27, shape=(96, 4); Great!
Array #28, shape=(356, 4);

In [301]:
len(good_data_idx)

3681

In [303]:
good_data_container = data_container[good_data_idx]
good_data_container

array([array([[0, 0, 48, 36],
       [0, 0, 48, 36],
       [0, 0, 0, 0],
       ...,
       [72, 60, 48, 36],
       [0, 0, 0, 0],
       [72, 60, 48, 36]], dtype=object),
       array([[0, 0, 48, 36],
       [0, 0, 48, 36],
       [0, 0, 0, 0],
       ...,
       [72, 60, 48, 36],
       [0, 0, 0, 0],
       [72, 60, 48, 36]], dtype=object),
       array([[65, 0, 0, 0],
       [65, 0, 0, 0],
       [67, 0, 0, 0],
       ...,
       [65, 72, 57, 41],
       [65, 72, 57, 41],
       [65, 72, 57, 41]], dtype=object),
       ...,
       array([[64, 61, 69, 45],
       [64, 61, 69, 45],
       [64, 61, 69, 45],
       [64, 61, 69, 45],
       [69, 64, 73, 57],
       [69, 64, 73, 57],
       [69, 64, 73, 57],
       [69, 64, 73, 57],
       [69, 64, 73, 56],
       [69, 64, 73, 56],
       [69, 64, 73, 56],
       [69, 64, 73, 56],
       [69, 61, 69, 54],
       [69, 61, 69, 54],
       [69, 61, 69, 54],
       [69, 61, 69, 54],
       [71, 64, 68, 52],
       [71, 64, 68, 52],
       [7

In [305]:
from sklearn.model_selection import train_test_split


train, test_valid = train_test_split(good_data_container, train_size = 0.6)
train

array([array([[66, 62, 59, 47],
       [66, 62, 59, 47],
       [66, 62, 59, 47],
       ...,
       [68, 64, 59, 49],
       [68, 64, 59, 49],
       [68, 64, 59, 49]], dtype=object),
       array([[64, 0, 0, 0],
       [64, 0, 0, 0],
       [64, 0, 0, 0],
       ...,
       [79, 67, 62, 55],
       [79, 67, 62, 55],
       [79, 67, 62, 55]], dtype=object),
       array([[74, 0, 0, 0],
       [75, 0, 0, 0],
       [75, 0, 0, 0],
       ...,
       [75, 70, 67, 51],
       [75, 70, 67, 51],
       [75, 70, 67, 51]], dtype=object),
       ...,
       array([[69, 64, 60, 45],
       [69, 64, 60, 45],
       [69, 64, 60, 45],
       ...,
       [69, 64, 60, 57],
       [69, 64, 60, 57],
       [69, 64, 60, 57]], dtype=object),
       array([[67, 63, 0, 0],
       [67, 63, 0, 0],
       [67, 63, 0, 0],
       [67, 63, 0, 0],
       [60, 67, 0, 0],
       [60, 67, 0, 0],
       [60, 67, 0, 0],
       [60, 67, 0, 0],
       [72, 68, 0, 0],
       [72, 68, 0, 0],
       [72, 68, 0, 0],
      

In [306]:
test, valid = train_test_split(test_valid, train_size = 0.5)
test

array([array([[0, 0, 0, 38],
       [0, 0, 0, 38],
       [0, 0, 0, 45],
       ...,
       [74, 65, 57, 50],
       [74, 65, 57, 50],
       [74, 65, 57, 50]], dtype=object),
       array([[0, 65, 57, 50],
       [0, 65, 57, 50],
       [74, 65, 57, 50],
       ...,
       [62, 62, 53, 50],
       [62, 62, 53, 50],
       [62, 62, 53, 50]], dtype=object),
       array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       ...,
       [73, 65, 56, 49],
       [73, 65, 56, 49],
       [73, 65, 56, 49]], dtype=object),
       array([[65, 77, 53, 0],
       [65, 77, 53, 0],
       [65, 77, 53, 0],
       ...,
       [75, 63, 53, 44],
       [75, 63, 53, 44],
       [75, 63, 53, 44]], dtype=object),
       array([[83, 79, 59, 43],
       [83, 79, 59, 43],
       [83, 79, 59, 43],
       ...,
       [72, 60, 60, 36],
       [72, 60, 60, 36],
       [72, 60, 60, 36]], dtype=object),
       array([[0, 0, 0, 47],
       [0, 0, 0, 47],
       [0, 0, 0, 47],
       ...,
       [62, 62, 

In [307]:
valid

array([array([[74, 0, 0, 62],
       [74, 0, 0, 62],
       [74, 0, 0, 62],
       ...,
       [74, 69, 53, 38],
       [74, 69, 53, 38],
       [74, 69, 53, 38]], dtype=object),
       array([[0, 0, 0, 45],
       [0, 0, 0, 45],
       [0, 0, 0, 45],
       ...,
       [71, 62, 61, 45],
       [69, 61, 57, 45],
       [69, 61, 57, 45]], dtype=object),
       array([[70, 0, 0, 46],
       [70, 0, 0, 46],
       [70, 0, 53, 46],
       ...,
       [62, 62, 58, 46],
       [62, 62, 58, 46],
       [62, 62, 58, 46]], dtype=object),
       array([[68, 0, 0, 0],
       [68, 0, 0, 0],
       [68, 0, 0, 0],
       ...,
       [68, 56, 68, 44],
       [68, 56, 68, 44],
       [68, 56, 68, 44]], dtype=object),
       array([[0, 0, 0, 38],
       [0, 0, 0, 38],
       [0, 0, 0, 38],
       ...,
       [74, 62, 50, 38],
       [74, 62, 50, 38],
       [74, 62, 50, 38]], dtype=object),
       array([[69, 0, 0, 45],
       [69, 0, 0, 45],
       [69, 0, 0, 45],
       ...,
       [81, 76, 60, 45],


In [308]:
train.shape, test.shape, valid.shape

((2208,), (736,), (737,))

In [25]:
with open('../data/stringquartet16thseparated.npz', 'wb') as f:
    np.savez(f, test=test, train=train, valid=valid)

In [17]:
import numpy as np

data = np.load('../data/stringquartet16thseparated.npz', allow_pickle=True)

In [18]:
train = data['train'].copy()
test = data['test'].copy()
valid = data['valid'].copy()

for array in train:
  array[array > 81] = np.nan
  array[array < 36] = np.nan

for array in test:
  array[array > 81] = np.nan
  array[array < 36] = np.nan

for array in valid:
  array[array > 81] = np.nan
  array[array < 36] = np.nan

In [3]:
with open('../data/stringquartet16thseparated.npz', 'wb') as f:
    np.savez(f, test=test, train=train, valid=valid)

In [24]:
from collections import Counter

sorted(Counter([array.max() for array in valid]).items())

[(36, 17),
 (37, 2),
 (38, 17),
 (39, 5),
 (40, 7),
 (41, 13),
 (42, 5),
 (43, 22),
 (44, 6),
 (45, 29),
 (46, 13),
 (47, 19),
 (48, 49),
 (49, 8),
 (50, 32),
 (51, 9),
 (52, 42),
 (53, 28),
 (54, 8),
 (55, 46),
 (56, 7),
 (57, 44),
 (58, 24),
 (59, 27),
 (60, 24),
 (61, 12),
 (62, 30),
 (63, 6),
 (64, 16),
 (65, 18),
 (66, 9),
 (67, 16),
 (68, 4),
 (69, 16),
 (70, 7),
 (71, 11),
 (72, 6),
 (74, 14),
 (75, 3),
 (76, 6),
 (77, 8),
 (78, 5),
 (79, 11),
 (80, 6),
 (81, 26),
 (nan, 4)]

In [23]:
sorted(Counter([array.min() for array in valid]).items())

[(36, 125),
 (37, 34),
 (38, 109),
 (39, 31),
 (40, 63),
 (41, 67),
 (42, 29),
 (43, 75),
 (44, 14),
 (45, 63),
 (46, 14),
 (47, 29),
 (48, 22),
 (49, 7),
 (50, 12),
 (51, 3),
 (52, 7),
 (53, 9),
 (54, 1),
 (55, 6),
 (57, 3),
 (58, 3),
 (61, 2),
 (62, 2),
 (nan, 4),
 (59, 2),
 (64, 1)]